version: '3.7'

services:
  servidor-php:
    image: fjortegan/dwes:php
    stdin_open: true
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./codigo-php:/var/www/html/

  db:
    image: mariadb
    # restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: ejerciciosphp
      MYSQL_USER: paula
      MYSQL_PASSWORD: asd123
      MYSQL_ROOT_PASSWORD: asd123

  phpmyadmin:
    image: phpmyadmin
    # restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
